[package]
name = "fake-client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fake-client"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
interprocess = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
anyhow = { workspace = true }
